# fingerprinting.py
"""
Structured function fingerprints — compact, machine-readable representations of
Python functions that let AI assistants understand code without reading full source.

Three-tier system:
  Tier 0 (static)   — assembled from already-parsed AST data at ingest time. Free.
  Tier 1 (skeleton) — AST-extracted code skeleton; ~38% of source tokens. Free.
  Tier 2 (label)    — one-line behavior description generated by IBM Bob from the
                       skeleton; cached permanently. ~100 tokens per function.

Token efficiency: 20 blast-radius functions via fingerprints ≈ 600 tokens.
                  Same 20 functions via full source ≈ 9,400 tokens.
"""

import ast
import re
import textwrap
from typing import Optional


# ---------------------------------------------------------------------------
# Tier 0 — Static fingerprint
# ---------------------------------------------------------------------------

def build_static_fingerprint(
    name: str,
    qualname: str,
    params: list[str],
    return_annotation: Optional[str],
    docstring: Optional[str],
    raises: list[str],
    calls: list[str],
    reads: list[str],
    caller_count: int = 0,
    behavior_label: Optional[str] = None,
) -> str:
    """Build a compact structured fingerprint from already-parsed function data.

    All inputs come from the parser + graph — no source code reading required.
    The returned string is stored as f.fingerprint in FalkorDB and served to
    Bob via get_function_fingerprints() as a dense context alternative to source.
    """
    # Signature line
    ret = f" → {return_annotation}" if return_annotation else ""
    sig = f"{name}({', '.join(params)}){ret}"

    lines = [sig]

    # Behavior label (Tier 2, written back by Bob; shown first if present)
    if behavior_label and behavior_label.strip():
        lines.append(f"// {behavior_label.strip()}")
    elif docstring and docstring.strip():
        # First sentence of docstring as behavior hint
        first = docstring.strip().split("\n")[0].split(".")[0].strip()
        if first:
            lines.append(f"// {first[:120]}")

    # Structural fields
    if calls:
        # Show short names (last FQN component), cap at 6
        short_calls = [c.split(".")[-1] for c in calls[:6]]
        if len(calls) > 6:
            short_calls.append(f"…+{len(calls)-6}")
        lines.append(f"calls: {', '.join(short_calls)}")

    if reads:
        lines.append(f"reads: {', '.join(reads[:4])}")

    if raises:
        lines.append(f"raises: {', '.join(raises[:4])}")

    lines.append(f"callers: {caller_count}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Tier 1 — Code skeleton
# ---------------------------------------------------------------------------

class _SkeletonTransformer(ast.NodeTransformer):
    """AST transformer that strips implementation noise, preserving structure."""

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.AST:
        # Keep the function def, recurse into body
        self.generic_visit(node)
        return node

    visit_AsyncFunctionDef = visit_FunctionDef

    def visit_Expr(self, node: ast.Expr) -> Optional[ast.AST]:
        # Keep docstrings (first statement if it's a string constant)
        if isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            # Truncate long docstrings to first line
            doc = node.value.value.strip().split("\n")[0][:80]
            node.value = ast.Constant(value=doc)
            return node
        # Drop bare expression statements (logging, assertions, etc.)
        return None

    def visit_Assign(self, node: ast.Assign) -> ast.AST:
        # Keep left-hand sides, replace RHS with Ellipsis
        node.value = ast.Constant(value=...)
        return node

    def visit_AnnAssign(self, node: ast.AnnAssign) -> ast.AST:
        # Keep type annotation, replace value with Ellipsis
        if node.value is not None:
            node.value = ast.Constant(value=...)
        return node

    def visit_AugAssign(self, node: ast.AugAssign) -> ast.AST:
        # Keep target and op, replace value with Ellipsis
        node.value = ast.Constant(value=...)
        return node

    def visit_Call(self, node: ast.Call) -> ast.AST:
        # Keep function name, drop all arguments
        node.args = []
        node.keywords = []
        return node

    def visit_Constant(self, node: ast.Constant) -> ast.AST:
        # Replace long string literals with placeholder
        if isinstance(node.value, str) and len(node.value) > 40:
            return ast.Constant(value="...")
        return node

    def visit_Import(self, node: ast.Import) -> Optional[ast.AST]:
        return None  # drop imports inside functions

    def visit_ImportFrom(self, node: ast.ImportFrom) -> Optional[ast.AST]:
        return None


def build_code_skeleton(source_code: str) -> str:
    """Extract a structural skeleton from Python source code.

    Keeps: function signature, control-flow conditions (if/for/while/try),
    return statements, raise statements, variable assignment LHS with types.
    Strips: string literals > 40 chars, call arguments, import statements,
    bare expression statements (logging, comments).

    Typical compression: ~38% of original character count.
    Quality: sufficient for an LLM to infer a behavior label without full source.

    Returns the skeleton as a string, or the original source on parse failure.
    """
    # Dedent first so ast.parse doesn't complain about indentation
    src = textwrap.dedent(source_code)
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return source_code  # fall back to full source

    transformer = _SkeletonTransformer()
    new_tree = transformer.visit(tree)
    ast.fix_missing_locations(new_tree)

    try:
        return ast.unparse(new_tree)
    except Exception:
        return source_code


# ---------------------------------------------------------------------------
# Helpers for fingerprint parsing (used by MCP tools to update labels)
# ---------------------------------------------------------------------------

def inject_behavior_label(fingerprint: str, label: str) -> str:
    """Insert or replace the behavior label line (// ...) in a fingerprint string."""
    clean_label = label.strip().lstrip("/").strip()[:120]
    if not fingerprint or not fingerprint.strip():
        return f"// {clean_label}"
    lines = fingerprint.split("\n")
    sig_line = lines[0]
    rest = [l for l in lines[1:] if not l.startswith("//")]
    return "\n".join([sig_line, f"// {clean_label}"] + rest)
